### ISSUE TITLE
ugly construction in about

### ISSUE THREAD

**Issue by ebolker** [jjliang/databaseui#105]
The repeated word in "Food Web Builder is built on ..." is clumsy. Rewrite.

Team members should be acknowledged by name somewhere (on this page?)

**Comment by jjliang** [comment]
I changed the layout of the about, I left some up as todo for now. The content of the tab-panes needs to be updated, After update we will push to the staging.

**Comment by jjliang** [comment]
I hope that is a better fix. Feel free to send more feed back if the about is still not up to par
