### ISSUE TITLE
Change routes for data Creation

### ISSUE THREAD

**Issue by diceydawg** [jjliang/databaseui#118]
Currently when you add something to the database outside of rails admin it takes you to the index page.  Should be changed appropriately so that users dont have to back and navigate anymore than necessary

**Comment by jjliang** [comment]
This is because of the controllers generated by scaffolding

**Comment by jjliang** [comment]
I'm working on this

**Comment by jjliang** [comment]
Done for the current data that we can enter through dashbaord
