### ISSUE TITLE
Relate authors and citations through authors_cite

### ISSUE THREAD

**Issue by kevb0001** [jjliang/databaseui#127]
When we create a citation, we need to create a new author_cite entry relating the ids of the citation and the author.

**Comment by jjliang** [comment]
I added fields in the new citations view for this not completely implemented with the javascript yet as javascript does not have a subsitute for the php list

**Comment by jjliang** [comment]
I have coded some of the javascript to print out the java script array. However, the collection.select does need to be changed to an autocomplete function most likely by author's last name.

**Comment by jjliang** [comment]
I added the javascript now it add and it prints the author_id. This still most likely needs to get changed to a ajax to display the listing name

**Comment by jjliang** [comment]
Also cannot enter duplicate authors, or the prompt, alerts have been set

**Comment by jjliang** [comment]
ok thanks to help from DiceK the authors now display on the citations page correctly after adding. Now what is left is getting the author_id's out of the myAuthors array and inserting it into the author_cite table after creating of the citation

**Comment by jjliang** [comment]
This is now functional
