### ISSUE TITLE
Interactions page

### ISSUE THREAD

**Issue by kevb0001** [jjliang/databaseui#131]
Interactions needs to be backed up by citations, so we need an auto-complete-by-title field and an option to create a new citation if a citation for the interaction does not already exist.

**Comment by diceydawg** [comment]
I'm going to place this on a hold until we meet with Jarrett about because we cannot use kelpforest atm

**Comment by jjliang** [comment]
This is a duplicate issue going to close now and use the issue that Sylvia created
