### ISSUE TITLE
The Google Map on dashboard view...

### ISSUE THREAD

**Issue by jhourani** [jjliang/databaseui#148]
I created a new account, got approved, and when I logged in for the first time my map is in the middle of the ocean, off the coast of Africa actually. Is this intentional? I thought it was broken at first because its just all blue, I thought it was going to be a view of the NE kelp forest or something like that, no?

**Comment by diceydawg** [comment]
so for a user you can only see regions that are part of your project.  The NE kelpforest is part of the testing project i believe

**Comment by jhourani** [comment]
But I saw the South Atlantic Ocean off the East coast of Africa when it loaded up.

**Comment by diceydawg** [comment]
by default the google maps points at the center of the map if there are not regions.  If you could post an image or something that would help us track down the problem.

**Comment by jjliang** [comment]
Not sure how but the regions seemed to have disappeared so I created one called mass

**Comment by diceydawg** [comment]
must of been deleted by someone.  I'm going to close the issue since it seems this issue is resolved.
