### ISSUE TITLE
Cannot add new node

### ISSUE THREAD

**Issue by jhourani** [jjliang/databaseui#150]
I tried creating a new node, using the data automatically generated when I entered `New Zealand Falcon`. After I clicked create node, the following URL returned an error saying something went wrong:

`http://databaseui.herokuapp.com/nodes`

**Comment by jjliang** [comment]
Validation for functional group has to be added so error is thrown instead of something went wrong. Basically we need to add all the validations for the fields

**Comment by diceydawg** [comment]
weird when i went through it created a node fine.  Jordan did you also populate the functional group and native status?

**Comment by jhourani** [comment]
No I did not do that, I just tried to create a node with the info that was generated. Either way, the URL should not return an error, maybe just display an error message to the user in the current view?

**Comment by diceydawg** [comment]
your right.  Unfortunately we havent gone around to implementing every validation for our models.

**Comment by diceydawg** [comment]
Fixed for the time being.
