### ISSUE TITLE
The Add author button on the citation page doesn't do anything

### ISSUE THREAD

**Issue by ludamillion** [jjliang/databaseui#169]
It appears that it is supposed to either pop up a form or redirect to the add author page. It does neither. The onClick method associated with it "addAuthor()" does not seem to be defined either on the page or anywhere in the javascript asset files.

**Comment by jjliang** [comment]
Add author button and method is defined in citation.js. I am working on this right note

**Comment by jjliang** [comment]
The add author button is to add author to the citations which now creates an author cite record after
