### ISSUE TITLE
Exporting data

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#21]
We need to setup an exporting function for the data in the database

**Comment by jjliang** [comment]
Rails_admin already has an export method but the user must have access to rails admin to use it. Now we have to consider if any user can export if so we need a new tab for it and view

**Comment by diceydawg** [comment]
we need to be careful of exporting I'd say.  I would rather only export
like lets say once a day and then let anyone download the data (.csv etc)
as opposed to letting people manually exporting.  Besides that only people
with admin access should be able to manually export.

Daisuke

**Comment by jjliang** [comment]
Ok closing issue since exporting for now is done in the rails admin engine
