### ISSUE TITLE
testing current build

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#23]
Rails has built in testing or do we want to just test it manually

**Comment by diceydawg** [comment]
We can use rails Validations and then place things in the test folder to test your backend.  The frontend we might need people to try out th website and find bugs

**Comment by diceydawg** [comment]
Tom recommended we use Cucumber for testing

**Comment by jjliang** [comment]
I spoke with Ethan, He does not want us to use unit testing as in Cucumber or Rspec, He would like us to preform live testing on the staging server, This will be a on going issue so closing it out of release 0.75
