### ISSUE TITLE
Presentation poster for  New England Undergraduate Computing Symposium

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#24]
We need to also create a presentation poster

**Comment by jjliang** [comment]
We need a draft of this poster by April 10th

**Comment by LuciusXRenault** [comment]
An idea for the poster that I am tooling around with is:
Logo and Title centered at the top,  with the mission statement or a brief summary of the project underneath.  
Then some key points or a list of features, with either screen shots or images of what the final product would look like .  

Thoughts?

**Comment by diceydawg** [comment]
We prob should get together for a short time to create/finish the poster.  I'm no good with graphics so I wont be able to help much with making things look pretty.

**Comment by LuciusXRenault** [comment]
I am having car trouble; should be fixed by tuesday, but I may be late to class.

**Comment by sylvia-sp** [comment]
I can help with the poster design.

On Sun, Apr 7, 2013 at 10:30 PM, LuciusXRenault notifications@github.comwrote:

> I am having car trouble; should be fixed by tuesday, but I may be late to
> class.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjliang/databaseui/issues/24#issuecomment-16029748
> .

##

**Comment by yujerlin** [comment]
Here is the poster I have so far. I shortened the abstract Kevin made
because it was a bit too big for poster. If you guys can take a look and
see if we need to change anything on abstract.  Also I am not sure which
screenshot we should use on the poster. If there is anything needed to
change please let me know or feel free to edit it.

**Comment by jjliang** [comment]
Where is it?

**Comment by yujerlin** [comment]
I attached it to the email because github doesn't support uploading files bigger than 5mb

**Comment by yujerlin** [comment]
https://docs.google.com/file/d/0B_6toVfPOhTDVXROZ2dwQkhGUjQ/edit?usp=sharing

**Comment by jjliang** [comment]
I see there is space in a for a 2nd column to add maybe some screen shots
of the application

**Comment by jjliang** [comment]
Can we also change the text color to black instead purple make it easier to
read

**Comment by yujerlin** [comment]
I've shared an item with you:

poster.pptx
https://docs.google.com/file/d/0B_6toVfPOhTDMkk4bG0xYU5zczg/edit?usp=sharing&invite=CP34kvMN

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by yujerlin** [comment]
*
https://docs.google.com/file/d/0B_6toVfPOhTDMkk4bG0xYU5zczg/edit?usp=sharing
*

Here is what I have so far. I am not sure what screen shot I could use
beside the data entry page. Does anyone have any idea what else I should
put? and if there is anything looks weird feel free to edit it.

**Comment by yujerlin** [comment]
We need to finalize the poster before I send it to Allison. Can you guys
take a look and see if there is anything needed to be changed? If not I'll
just send it to Allison later today.
https://docs.google.com/file/d/0B_6toVfPOhTDNjBQVmMzSFRnZVk/edit

**Comment by diceydawg** [comment]
honestly I think the right side is totally unnecessary.  We should include all the names in one bubble so that the names dont take up so much of the poster.

**Comment by kevb0001** [comment]
Either way, Yujer I think you did an excellent job revamping the poster.
Looks good to me.

-Kevin

**Comment by jjliang** [comment]
Uh the text is not readable

**Comment by jjliang** [comment]
I notice the text alignment is off in a place

**Comment by jjliang** [comment]
Please also shrink the icons on the banner so that the icons aren't cut off
by the border lines

**Comment by yujerlin** [comment]
Thanks for the feedback. I fixed it and made some change. please take a
look again and let me know if anything needed to be changed.
https://docs.google.com/file/d/0B_6toVfPOhTDNTROeGxvSmE5bk0/edit?usp=sharing

**Comment by jjliang** [comment]
I'm fine with this given our time constraints
