### ISSUE TITLE
tab for user account approvals

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#37]
We need a tab to approve user accounts for admins

**Comment by jjliang** [comment]
Luke I edited the dashboard index, let me know if you like that idea. I also put in a user tab for the admin role for now

**Comment by jjliang** [comment]
Ok so listing the users has >>>>> at the top of the table, I looked at the html.erb files I don't see it , I'm not sure if you can find where that is coming from.

**Comment by diceydawg** [comment]
i believe the >>>> is an artifact from git's merging conflicts.

**Comment by jjliang** [comment]
This issue was fixed last night
