### ISSUE TITLE
Enumerating an attribute in a model

### ISSUE THREAD

**Issue by kevb0001** [jjliang/databaseui#4]
Need to figure out how to enumerate an attribute in a model like in the 'citations' table.

**Comment by jjliang** [comment]
Closing this as we do not want to use enums I thought.

**Comment by diceydawg** [comment]
I thought he meant enumerate the tables and not the ENUM data type.

Daisuke

**Comment by diceydawg** [comment]
http://edgeguides.rubyonrails.org/active_record_querying.html 

This is a good guide in understanding how to query the database.
