### ISSUE TITLE
Make GoogleMap viewable on main page

### ISSUE THREAD

**Issue by ludamillion** [jjliang/databaseui#42]
As a result of yesterdays meeting it would be best if the Map was viewable on the main page to anyone who visits the site not just signed in users.

**Comment by diceydawg** [comment]
ok I can make that change.  Also do we still need the world map?

**Comment by ludamillion** [comment]
No we don't. That was just a place holder for the Google Map

**Comment by jjliang** [comment]
I commented out the maps as in the dashboard controler @city was causing an issue. I talked to Tom a bit but haven't had a chance to go through the code besides commenting out the errors. He said we should most likely just link to the google maps api instead of using the gmpas4rails gem

**Comment by diceydawg** [comment]
Done
