### ISSUE TITLE
sceuring database.yml

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#56]
we need to hide the user name and password

**Comment by sylvia-sp** [comment]
If we get Capistrano working we can use it to generate database.yml. See
example below.

http://www.simonecarletti.com/blog/2009/06/capistrano-and-database-yml/

On Sat, Apr 6, 2013 at 11:20 PM, John Liang notifications@github.comwrote:

> we need to hide the user name and password
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjliang/databaseui/issues/56
> .

##

**Comment by jjliang** [comment]
I got that done

**Comment by jjliang** [comment]
this is done
