### ISSUE TITLE
Fixing the dashboard index landing page

### ISSUE THREAD

**Issue by jjliang** [jjliang/databaseui#69]
How would we like to design the main dashboard landing page. I am not sure if Luke had something in mind , but I think project lead should have a tab that links to dice k gmaps to draw a region for the project.

**Comment by diceydawg** [comment]
Should I just embed the editing region stuff in a tab in the dashboard for lead then?

**Comment by jjliang** [comment]
Dice K can we have a sumbit or create button to save the regions please, and also what is up with the slider on landing page for dashboard

**Comment by diceydawg** [comment]
thats probably cause the map size is larger than the container it is in.

**Comment by diceydawg** [comment]
can you explain what you mean by slider?

**Comment by jjliang** [comment]
I fixed the slider for now
