### ISSUE TITLE
Auto Complete CSS is not working

### ISSUE THREAD

**Issue by diceydawg** [jjliang/databaseui#82]
I got auto complete to work with working_name however because the css is not being generated correctly it looks like a mess.

**Comment by diceydawg** [comment]
Forgot to include js and css files.   I'll include the fixes in my next commit

**Comment by jjliang** [comment]
I don't like auto complete or these jquery.js scripts ..... causing errors when pushing to staging server

**Comment by diceydawg** [comment]
gg

**Comment by jjliang** [comment]
should we try this gem instead 
http://rubygems.org/gems/rails3-jquery-autocomplete

**Comment by diceydawg** [comment]
were using that gem
lol
