### ISSUE TITLE
Feedback page

### ISSUE THREAD

**Issue by diceydawg** [jjliang/databaseui#83]
we need a feedback page when people use the site.

**Comment by ebolker** [comment]
You don't necessarily need a feedback page - you need a good way to
get feedback. It's OK to provide a link to your github issues (open in
another tab in the browser, so the user can see what she was looking
at on the site while entering the bug).

A "send a message" window would do too.

**Comment by jjliang** [comment]
I will ask Kevin to put a link to report bugs in the help section tab

**Comment by kevb0001** [comment]
I'll will put up some form of link tonight for this function.

-Kevin
