### ISSUE TITLE
Rails Migration

### ISSUE THREAD

**Issue by diceydawg** [jjliang/databaseui#92]
Whenever you decide to change the database structure please create a new migration with the appropriate up and down for rollbacking purposes. if necessary

Also test the migrations by running: (You'll lose all database entries not in seed!)
rake db:drop
rake db:create
rake db:migrate
rake db:seed

This is important because if someone wanted to contribute/build the code they have to run every migration from the start.

Also some of us are editing the migrations instead of creating new ones which can cause issues in other migrations.   When you add/delete columns to tables if you need default values then make sure to add it to the defaults and nils.rb.  Tables that are removed should also be removed in defaults and nils.   Defaults and nils should always be the last migration.

**Comment by jjliang** [comment]
At this moment we should be out of the habit of dropping and creating, if there is data in the database we don't want to lose it. Also the latest modifications to the migrations has left my db:migrate broken.

**Comment by jjliang** [comment]
had to run a rake db:reset, also it migrations is not working on the staging server either

**Comment by diceydawg** [comment]
db:reset may not work because the schema.rb does not reflect the actual
schema.  db:reset calls db:drop then db:schema:load db:schema:seed.
  if you edit the migrations without making new ones rails does not
generate a new schema.rb based upon the migration because the schema version is assumed to be up to date.
 To force it to migrate you can change
the assumed schema version to a earlier timestamp then run db:migrate.
Point is if you run a migration then editing will not do anything unless you run every migration from the start.

**Comment by jjliang** [comment]
issue isn't about forcing it to work. Issue is having to drop the data, If this was running on a production server we would not want to drop the data just to run migrations

**Comment by diceydawg** [comment]
you could try changing the schema version to an earlier one and forceit to run some migrations.  The problem is that the schema.rb isn't correct.  For keeping the data it shouldnt be a problem as long as we give default values  for new columns.

**Comment by jjliang** [comment]
Closing this issue, hoping all understand to create new migration files when changing the database
