### ISSUE TITLE
Approving regions

### ISSUE THREAD

**Issue by diceydawg** [jjliang/databaseui#93]
If someone in a project creates a region should it be approved by the admin/lead/mod?
Same question for citations, authors and nodes.

**Comment by jjliang** [comment]
I want to say only let project leads create regions. Also there is no way to save a region after selecting it at the moment

**Comment by diceydawg** [comment]
Im my local build I'm just passing things using the rails form helpers form
a twitter bootstrap modal menu.  I think its a safe way to do things but
well see

**Comment by jjliang** [comment]
Is this still an issue? Project Lead creates regions not the moderator, moderator moderates data, not the region. Also can we have some type of submit button to save the data for the region
