### ISSUE TITLE
Gmaps

### ISSUE THREAD

**Issue by kevb0001** [jjliang/databaseui#98]
When you double click on Gmaps to zoom in, it spits back a dialog box of the coordinates you clicked on that you have to confirm before it zooms in.

**Comment by diceydawg** [comment]
intended lol.  I put it in as a test for the map.  I'll make sure to get
rid of it when the gmaps redions editor is finished.

**Comment by jjliang** [comment]
Will this be done b release 0.75 if not please reassign to release 1.0
